/**
 * Build-time audio manifest access. The manifest is generated by
 * falsafa-audio/pipeline/align_merge.py from the forced-alignment pass;
 * a work/chapter appears in it only when its audio AND word alignment are
 * complete, so pages degrade gracefully while coverage grows.
 */
import manifest from "../data/audio-manifest.json";

interface ManifestEntry {
  dur: number;
  tracks: string[];
  streams: { id: string; url: string }[];
  chapters: Record<string, number>;
}

const works = manifest as Record<string, ManifestEntry>;

export function workAudio(slug: string): ManifestEntry | null {
  return works[slug] ?? null;
}

export function chapterAudio(
  slug: string,
  chapter: string,
): { durMs: number; streams: { id: string; url: string }[] } | null {
  const w = works[slug];
  const durMs = w?.chapters?.[chapter];
  if (!w || durMs === undefined) return null;
  return { durMs, streams: w.streams };
}

/** "1 hr 42 min" / "23 min" — for chrome labels. */
export function fmtDuration(ms: number): string {
  const min = Math.round(ms / 60000);
  if (min < 60) return `${Math.max(1, min)} min`;
  const h = Math.floor(min / 60);
  const m = min % 60;
  return m ? `${h} hr ${m} min` : `${h} hr`;
}
