// AUTO-GENERATED by apps/a11y-tools/src/generate/matrix.ts.
// Do not edit by hand. Run: bun a11y:generate matrix.
// Source: docs/accessibility/conformance.yaml

export interface ConformanceCriterion {
  id: string;
  name: string;
  level: "A" | "AA" | "AAA";
  status: "supports" | "partial" | "not-applicable" | "does-not-support";
  exception?: string;
  notes: string;
  evidence: Array<{ kind: "source" | "test" | "artifact"; path: string; lines?: string; anchor?: string }>;
  commit: string;
}

export interface Section508Entry {
  id: string;
  name: string;
  status: ConformanceCriterion["status"];
  notes?: string;
  evidence: ConformanceCriterion["evidence"];
}

export interface EN301549Entry {
  clause: string;
  name: string;
  status: ConformanceCriterion["status"];
  notes?: string;
  evidence: ConformanceCriterion["evidence"];
}

export interface ConformanceDoc {
  meta: {
    standard: string;
    conformance_level: string;
    partial_aaa: boolean;
    last_review: string;
    next_review: string;
    contact: string;
    vpat_version: string;
    jurisdictions: string[];
  };
  criteria: ConformanceCriterion[];
  section_508: Section508Entry[];
  en_301_549: EN301549Entry[];
}

export const CONFORMANCE: ConformanceDoc = {
  "meta": {
    "standard": "WCAG 2.2",
    "conformance_level": "AA",
    "partial_aaa": true,
    "last_review": "2026-05-14",
    "next_review": "2026-08-14",
    "contact": "accessibility@thothica.com",
    "vpat_version": "2.5 INT",
    "jurisdictions": [
      "india",
      "eu",
      "us"
    ]
  },
  "criteria": [
    {
      "id": "1.1.1",
      "name": "Non-text Content",
      "level": "A",
      "status": "does-not-support",
      "notes": "TBD V1",
      "evidence": [],
      "commit": "0000000"
    },
    {
      "id": "1.2.1",
      "name": "Audio-only and Video-only (Prerecorded)",
      "level": "A",
      "status": "not-applicable",
      "exception": "no-audio-or-video-content",
      "notes": "Falsafa is a text-only reading platform. No audio or video content is published.",
      "evidence": [],
      "commit": "0000000"
    },
    {
      "id": "1.2.2",
      "name": "Captions (Prerecorded)",
      "level": "A",
      "status": "not-applicable",
      "exception": "no-audio-or-video-content",
      "notes": "No video content.",
      "evidence": [],
      "commit": "0000000"
    },
    {
      "id": "1.2.3",
      "name": "Audio Description or Media Alternative (Prerecorded)",
      "level": "A",
      "status": "not-applicable",
      "exception": "no-audio-or-video-content",
      "notes": "No video content.",
      "evidence": [],
      "commit": "0000000"
    },
    {
      "id": "1.3.1",
      "name": "Info and Relationships",
      "level": "A",
      "status": "supports",
      "notes": "Semantic HTML throughout — header/main/nav/footer/article landmarks, heading hierarchy h1→h6, <table> with <th scope> in the conformance matrix, <dl>/<dt>/<dd> for description lists, <details>/<summary> for collapsibles.\n",
      "evidence": [
        {
          "kind": "source",
          "path": "apps/site/src/components/ConformanceMatrix.astro",
          "anchor": "scope=\"col\""
        },
        {
          "kind": "source",
          "path": "apps/site/src/layouts/Base.astro",
          "anchor": "<main"
        },
        {
          "kind": "artifact",
          "path": "docs/accessibility/test-runs/homepage/latest/transcript-synthetic.md"
        }
      ],
      "commit": "HEAD"
    },
    {
      "id": "1.3.2",
      "name": "Meaningful Sequence",
      "level": "A",
      "status": "does-not-support",
      "notes": "TBD V1",
      "evidence": [],
      "commit": "0000000"
    },
    {
      "id": "1.3.3",
      "name": "Sensory Characteristics",
      "level": "A",
      "status": "does-not-support",
      "notes": "TBD V1",
      "evidence": [],
      "commit": "0000000"
    },
    {
      "id": "1.4.1",
      "name": "Use of Color",
      "level": "A",
      "status": "does-not-support",
      "notes": "TBD V1",
      "evidence": [],
      "commit": "0000000"
    },
    {
      "id": "1.4.2",
      "name": "Audio Control",
      "level": "A",
      "status": "not-applicable",
      "exception": "no-audio-or-video-content",
      "notes": "No auto-playing audio.",
      "evidence": [],
      "commit": "0000000"
    },
    {
      "id": "2.1.1",
      "name": "Keyboard",
      "level": "A",
      "status": "supports",
      "notes": "All interactive controls are keyboard-operable. The search combobox handles ↓/↑/Enter without leaving the input. Dialog opens/closes via Cmd+K / Escape.\n",
      "evidence": [
        {
          "kind": "source",
          "path": "apps/site/src/components/SearchDialog.astro",
          "anchor": "ArrowDown"
        },
        {
          "kind": "artifact",
          "path": "docs/accessibility/test-runs/search/latest/transcript-synthetic.md"
        }
      ],
      "commit": "HEAD"
    },
    {
      "id": "2.1.2",
      "name": "No Keyboard Trap",
      "level": "A",
      "status": "does-not-support",
      "notes": "TBD V1",
      "evidence": [],
      "commit": "0000000"
    },
    {
      "id": "2.1.4",
      "name": "Character Key Shortcuts",
      "level": "A",
      "status": "does-not-support",
      "notes": "TBD V1",
      "evidence": [],
      "commit": "0000000"
    },
    {
      "id": "2.2.1",
      "name": "Timing Adjustable",
      "level": "A",
      "status": "does-not-support",
      "notes": "TBD V1",
      "evidence": [],
      "commit": "0000000"
    },
    {
      "id": "2.2.2",
      "name": "Pause, Stop, Hide",
      "level": "A",
      "status": "does-not-support",
      "notes": "TBD V1",
      "evidence": [],
      "commit": "0000000"
    },
    {
      "id": "2.3.1",
      "name": "Three Flashes or Below Threshold",
      "level": "A",
      "status": "does-not-support",
      "notes": "TBD V1",
      "evidence": [],
      "commit": "0000000"
    },
    {
      "id": "2.4.1",
      "name": "Bypass Blocks",
      "level": "A",
      "status": "supports",
      "notes": "Skip-link on every page targets <main id=\"main\">. Skip-link is visible on focus and reaches main in one keystroke.\n",
      "evidence": [
        {
          "kind": "source",
          "path": "apps/site/src/layouts/Base.astro",
          "anchor": "href=\"#main\""
        },
        {
          "kind": "artifact",
          "path": "docs/accessibility/test-runs/homepage/latest/transcript-synthetic.md"
        }
      ],
      "commit": "HEAD"
    },
    {
      "id": "2.4.2",
      "name": "Page Titled",
      "level": "A",
      "status": "does-not-support",
      "notes": "TBD V1",
      "evidence": [],
      "commit": "0000000"
    },
    {
      "id": "2.4.3",
      "name": "Focus Order",
      "level": "A",
      "status": "does-not-support",
      "notes": "TBD V1",
      "evidence": [],
      "commit": "0000000"
    },
    {
      "id": "2.4.4",
      "name": "Link Purpose (In Context)",
      "level": "A",
      "status": "does-not-support",
      "notes": "TBD V1",
      "evidence": [],
      "commit": "0000000"
    },
    {
      "id": "2.5.1",
      "name": "Pointer Gestures",
      "level": "A",
      "status": "does-not-support",
      "notes": "TBD V1",
      "evidence": [],
      "commit": "0000000"
    },
    {
      "id": "2.5.2",
      "name": "Pointer Cancellation",
      "level": "A",
      "status": "does-not-support",
      "notes": "TBD V1",
      "evidence": [],
      "commit": "0000000"
    },
    {
      "id": "2.5.3",
      "name": "Label in Name",
      "level": "A",
      "status": "does-not-support",
      "notes": "TBD V1",
      "evidence": [],
      "commit": "0000000"
    },
    {
      "id": "2.5.4",
      "name": "Motion Actuation",
      "level": "A",
      "status": "does-not-support",
      "notes": "TBD V1",
      "evidence": [],
      "commit": "0000000"
    },
    {
      "id": "3.1.1",
      "name": "Language of Page",
      "level": "A",
      "status": "supports",
      "notes": "The root <html> emits lang=\"en\". Each variant article emits its own lang attribute via bcp47Of(), so screen readers switch voice when reading non-English variants.\n",
      "evidence": [
        {
          "kind": "source",
          "path": "apps/site/src/lib/corpus.ts",
          "anchor": "bcp47Of"
        },
        {
          "kind": "source",
          "path": "apps/site/src/layouts/Base.astro",
          "anchor": "lang=\"en\""
        }
      ],
      "commit": "HEAD"
    },
    {
      "id": "3.2.1",
      "name": "On Focus",
      "level": "A",
      "status": "does-not-support",
      "notes": "TBD V1",
      "evidence": [],
      "commit": "0000000"
    },
    {
      "id": "3.2.2",
      "name": "On Input",
      "level": "A",
      "status": "does-not-support",
      "notes": "TBD V1",
      "evidence": [],
      "commit": "0000000"
    },
    {
      "id": "3.2.6",
      "name": "Consistent Help",
      "level": "A",
      "status": "does-not-support",
      "notes": "TBD V1",
      "evidence": [],
      "commit": "0000000"
    },
    {
      "id": "3.3.1",
      "name": "Error Identification",
      "level": "A",
      "status": "does-not-support",
      "notes": "TBD V1",
      "evidence": [],
      "commit": "0000000"
    },
    {
      "id": "3.3.2",
      "name": "Labels or Instructions",
      "level": "A",
      "status": "does-not-support",
      "notes": "TBD V1",
      "evidence": [],
      "commit": "0000000"
    },
    {
      "id": "4.1.2",
      "name": "Name, Role, Value",
      "level": "A",
      "status": "supports",
      "notes": "All interactive controls have accessible names and explicit roles. The combobox/listbox pattern is the most complex case; other controls (buttons, dialogs, nav links) use semantic HTML.\n",
      "evidence": [
        {
          "kind": "source",
          "path": "apps/site/src/components/SearchDialog.astro",
          "anchor": "role=\"combobox\""
        },
        {
          "kind": "artifact",
          "path": "docs/accessibility/test-runs/search/latest/transcript-synthetic.md"
        }
      ],
      "commit": "HEAD"
    },
    {
      "id": "1.2.4",
      "name": "Captions (Live)",
      "level": "AA",
      "status": "not-applicable",
      "exception": "no-audio-or-video-content",
      "notes": "No live media.",
      "evidence": [],
      "commit": "0000000"
    },
    {
      "id": "1.2.5",
      "name": "Audio Description (Prerecorded)",
      "level": "AA",
      "status": "not-applicable",
      "exception": "no-audio-or-video-content",
      "notes": "No video content.",
      "evidence": [],
      "commit": "0000000"
    },
    {
      "id": "1.3.4",
      "name": "Orientation",
      "level": "AA",
      "status": "does-not-support",
      "notes": "TBD V1",
      "evidence": [],
      "commit": "0000000"
    },
    {
      "id": "1.3.5",
      "name": "Identify Input Purpose",
      "level": "AA",
      "status": "does-not-support",
      "notes": "TBD V1",
      "evidence": [],
      "commit": "0000000"
    },
    {
      "id": "1.4.3",
      "name": "Contrast (Minimum)",
      "level": "AA",
      "status": "supports",
      "notes": "Body text contrast: light 16.7:1, dark 14.8:1, sepia 11:1 — all exceed WCAG 1.4.3 4.5:1 minimum and also pass the AAA 7:1 ceiling. The accent-soft link-hover color is now darker (≥ 4.5:1 in all themes).\n",
      "evidence": [
        {
          "kind": "source",
          "path": "apps/site/src/styles/tokens.css",
          "anchor": "--ink"
        },
        {
          "kind": "source",
          "path": "apps/site/src/styles/tokens.css",
          "anchor": "--accent-soft"
        },
        {
          "kind": "test",
          "path": "scripts/__tests__/a11y-contrast-audit.test.ts",
          "lines": "1-47"
        },
        {
          "kind": "artifact",
          "path": "docs/accessibility/test-runs/contrast/latest/result.json"
        }
      ],
      "commit": "HEAD"
    },
    {
      "id": "1.4.4",
      "name": "Resize Text",
      "level": "AA",
      "status": "does-not-support",
      "notes": "TBD V1",
      "evidence": [],
      "commit": "0000000"
    },
    {
      "id": "1.4.5",
      "name": "Images of Text",
      "level": "AA",
      "status": "does-not-support",
      "notes": "TBD V1",
      "evidence": [],
      "commit": "0000000"
    },
    {
      "id": "1.4.10",
      "name": "Reflow",
      "level": "AA",
      "status": "does-not-support",
      "notes": "TBD V1",
      "evidence": [],
      "commit": "0000000"
    },
    {
      "id": "1.4.11",
      "name": "Non-text Contrast",
      "level": "AA",
      "status": "supports",
      "notes": "Every UI token pair (--rule, --accent-soft variants) measured ≥ 3:1 against its theme's paper background. Audit runs via `bun run a11y:contrast` in CI; non-text-contrast failures fail the build.\n",
      "evidence": [
        {
          "kind": "source",
          "path": "apps/site/src/styles/tokens.css",
          "anchor": "--rule"
        },
        {
          "kind": "source",
          "path": "apps/site/src/styles/tokens.css",
          "anchor": "--accent-soft"
        },
        {
          "kind": "test",
          "path": "scripts/__tests__/a11y-contrast-audit.test.ts",
          "lines": "1-47"
        },
        {
          "kind": "artifact",
          "path": "docs/accessibility/test-runs/contrast/latest/result.json"
        }
      ],
      "commit": "HEAD"
    },
    {
      "id": "1.4.12",
      "name": "Text Spacing",
      "level": "AA",
      "status": "does-not-support",
      "notes": "TBD V1",
      "evidence": [],
      "commit": "0000000"
    },
    {
      "id": "1.4.13",
      "name": "Content on Hover or Focus",
      "level": "AA",
      "status": "does-not-support",
      "notes": "TBD V1",
      "evidence": [],
      "commit": "0000000"
    },
    {
      "id": "2.4.5",
      "name": "Multiple Ways",
      "level": "AA",
      "status": "does-not-support",
      "notes": "TBD V1",
      "evidence": [],
      "commit": "0000000"
    },
    {
      "id": "2.4.6",
      "name": "Headings and Labels",
      "level": "AA",
      "status": "supports",
      "notes": "Every page has a single h1. Subsections use h2 with aria-labelledby pointers from <section>. Form inputs have explicit <label>.\n",
      "evidence": [
        {
          "kind": "source",
          "path": "apps/site/src/pages/accessibility.astro",
          "anchor": "aria-labelledby"
        }
      ],
      "commit": "HEAD"
    },
    {
      "id": "2.4.7",
      "name": "Focus Visible",
      "level": "AA",
      "status": "supports",
      "notes": "Site-wide :focus-visible style produces a high-contrast ring. (Enhanced 2.4.13 AAA focus appearance audit is V2 scope.)\n",
      "evidence": [
        {
          "kind": "source",
          "path": "apps/site/src/styles/global.css",
          "anchor": ":focus-visible"
        }
      ],
      "commit": "HEAD"
    },
    {
      "id": "2.4.11",
      "name": "Focus Not Obscured (Minimum)",
      "level": "AA",
      "status": "does-not-support",
      "notes": "TBD V1",
      "evidence": [],
      "commit": "0000000"
    },
    {
      "id": "2.5.7",
      "name": "Dragging Movements",
      "level": "AA",
      "status": "does-not-support",
      "notes": "TBD V1",
      "evidence": [],
      "commit": "0000000"
    },
    {
      "id": "2.5.8",
      "name": "Target Size (Minimum)",
      "level": "AA",
      "status": "does-not-support",
      "notes": "TBD V1",
      "evidence": [],
      "commit": "0000000"
    },
    {
      "id": "3.1.2",
      "name": "Language of Parts",
      "level": "AA",
      "status": "supports",
      "notes": "Non-English chapter variants emit lang=\"<bcp47>\" on the <article> wrapper rendered by Reader.astro. The /about page wraps foreign terms in <span lang=\"...\"> as they appear in prose. bcp47Of() normalizes corpus language/script names to ISO 639/15924.\n",
      "evidence": [
        {
          "kind": "source",
          "path": "apps/site/src/layouts/Reader.astro",
          "anchor": "lang={lang}"
        },
        {
          "kind": "source",
          "path": "apps/site/src/pages/works/[slug]/[chapter]/[variant].astro",
          "anchor": "bcp47Of"
        },
        {
          "kind": "source",
          "path": "apps/site/src/pages/about.astro",
          "anchor": "lang=\"sa-Latn\""
        },
        {
          "kind": "test",
          "path": "apps/site/src/lib/__tests__/corpus-bcp47.test.ts",
          "lines": "1-60"
        },
        {
          "kind": "artifact",
          "path": "docs/accessibility/test-runs/reader-original/latest/transcript-voiceover.md"
        }
      ],
      "commit": "HEAD"
    },
    {
      "id": "3.2.3",
      "name": "Consistent Navigation",
      "level": "AA",
      "status": "does-not-support",
      "notes": "TBD V1",
      "evidence": [],
      "commit": "0000000"
    },
    {
      "id": "3.2.4",
      "name": "Consistent Identification",
      "level": "AA",
      "status": "does-not-support",
      "notes": "TBD V1",
      "evidence": [],
      "commit": "0000000"
    },
    {
      "id": "3.3.3",
      "name": "Error Suggestion",
      "level": "AA",
      "status": "does-not-support",
      "notes": "TBD V1",
      "evidence": [],
      "commit": "0000000"
    },
    {
      "id": "3.3.4",
      "name": "Error Prevention (Legal, Financial, Data)",
      "level": "AA",
      "status": "does-not-support",
      "notes": "TBD V1",
      "evidence": [],
      "commit": "0000000"
    },
    {
      "id": "3.3.7",
      "name": "Redundant Entry",
      "level": "AA",
      "status": "not-applicable",
      "exception": "no-authentication",
      "notes": "No re-entry forms; site is read-only.",
      "evidence": [],
      "commit": "0000000"
    },
    {
      "id": "3.3.8",
      "name": "Accessible Authentication (Minimum)",
      "level": "AA",
      "status": "not-applicable",
      "exception": "no-authentication",
      "notes": "No authentication.",
      "evidence": [],
      "commit": "0000000"
    },
    {
      "id": "4.1.3",
      "name": "Status Messages",
      "level": "AA",
      "status": "supports",
      "notes": "Search dialog announces result count via aria-live=\"polite\" on the status string. The results list is a role=\"listbox\" with role=\"option\" items; the input is a role=\"combobox\" with aria-activedescendant, so screen readers announce each option change without leaving the input.\n",
      "evidence": [
        {
          "kind": "source",
          "path": "apps/site/src/components/SearchDialog.astro",
          "anchor": "role=\"combobox\""
        },
        {
          "kind": "source",
          "path": "apps/site/src/components/SearchDialog.astro",
          "anchor": "role=\"listbox\""
        },
        {
          "kind": "source",
          "path": "apps/site/src/components/SearchDialog.astro",
          "anchor": "aria-activedescendant"
        },
        {
          "kind": "source",
          "path": "apps/site/src/components/SearchDialog.astro",
          "anchor": "aria-live=\"polite\""
        },
        {
          "kind": "artifact",
          "path": "docs/accessibility/test-runs/search/latest/transcript-voiceover.md"
        }
      ],
      "commit": "HEAD"
    },
    {
      "id": "1.2.6",
      "name": "Sign Language (Prerecorded)",
      "level": "AAA",
      "status": "not-applicable",
      "exception": "no-audio-or-video-content",
      "notes": "No video content.",
      "evidence": [],
      "commit": "0000000"
    },
    {
      "id": "1.2.7",
      "name": "Extended Audio Description (Prerecorded)",
      "level": "AAA",
      "status": "not-applicable",
      "exception": "no-audio-or-video-content",
      "notes": "No video content.",
      "evidence": [],
      "commit": "0000000"
    },
    {
      "id": "1.2.8",
      "name": "Media Alternative (Prerecorded)",
      "level": "AAA",
      "status": "not-applicable",
      "exception": "no-audio-or-video-content",
      "notes": "No video content.",
      "evidence": [],
      "commit": "0000000"
    },
    {
      "id": "1.2.9",
      "name": "Audio-only (Live)",
      "level": "AAA",
      "status": "not-applicable",
      "exception": "no-audio-or-video-content",
      "notes": "No live media.",
      "evidence": [],
      "commit": "0000000"
    },
    {
      "id": "1.3.6",
      "name": "Identify Purpose",
      "level": "AAA",
      "status": "does-not-support",
      "notes": "TBD V1",
      "evidence": [],
      "commit": "0000000"
    },
    {
      "id": "1.4.6",
      "name": "Contrast (Enhanced)",
      "level": "AAA",
      "status": "does-not-support",
      "notes": "TBD V1",
      "evidence": [],
      "commit": "0000000"
    },
    {
      "id": "1.4.7",
      "name": "Low or No Background Audio",
      "level": "AAA",
      "status": "not-applicable",
      "exception": "no-audio-or-video-content",
      "notes": "No audio.",
      "evidence": [],
      "commit": "0000000"
    },
    {
      "id": "1.4.8",
      "name": "Visual Presentation",
      "level": "AAA",
      "status": "does-not-support",
      "notes": "TBD V1",
      "evidence": [],
      "commit": "0000000"
    },
    {
      "id": "1.4.9",
      "name": "Images of Text (No Exception)",
      "level": "AAA",
      "status": "does-not-support",
      "notes": "TBD V1",
      "evidence": [],
      "commit": "0000000"
    },
    {
      "id": "2.1.3",
      "name": "Keyboard (No Exception)",
      "level": "AAA",
      "status": "does-not-support",
      "notes": "TBD V1",
      "evidence": [],
      "commit": "0000000"
    },
    {
      "id": "2.2.3",
      "name": "No Timing",
      "level": "AAA",
      "status": "does-not-support",
      "notes": "TBD V1",
      "evidence": [],
      "commit": "0000000"
    },
    {
      "id": "2.2.4",
      "name": "Interruptions",
      "level": "AAA",
      "status": "does-not-support",
      "notes": "TBD V1",
      "evidence": [],
      "commit": "0000000"
    },
    {
      "id": "2.2.5",
      "name": "Re-authenticating",
      "level": "AAA",
      "status": "not-applicable",
      "exception": "no-authentication",
      "notes": "Site has no authentication of any kind.",
      "evidence": [],
      "commit": "0000000"
    },
    {
      "id": "2.2.6",
      "name": "Timeouts",
      "level": "AAA",
      "status": "does-not-support",
      "notes": "TBD V1",
      "evidence": [],
      "commit": "0000000"
    },
    {
      "id": "2.3.2",
      "name": "Three Flashes",
      "level": "AAA",
      "status": "does-not-support",
      "notes": "TBD V1",
      "evidence": [],
      "commit": "0000000"
    },
    {
      "id": "2.3.3",
      "name": "Animation from Interactions",
      "level": "AAA",
      "status": "supports",
      "notes": "The site honors prefers-reduced-motion: reduce by capping all animation/transition durations to 0.01ms. No motion-from-interaction effects are exempt.\n",
      "evidence": [
        {
          "kind": "source",
          "path": "apps/site/src/styles/tokens.css",
          "anchor": "prefers-reduced-motion"
        }
      ],
      "commit": "HEAD"
    },
    {
      "id": "2.4.8",
      "name": "Location",
      "level": "AAA",
      "status": "does-not-support",
      "notes": "TBD V1",
      "evidence": [],
      "commit": "0000000"
    },
    {
      "id": "2.4.9",
      "name": "Link Purpose (Link Only)",
      "level": "AAA",
      "status": "does-not-support",
      "notes": "TBD V1",
      "evidence": [],
      "commit": "0000000"
    },
    {
      "id": "2.4.10",
      "name": "Section Headings",
      "level": "AAA",
      "status": "does-not-support",
      "notes": "TBD V1",
      "evidence": [],
      "commit": "0000000"
    },
    {
      "id": "2.4.12",
      "name": "Focus Not Obscured (Enhanced)",
      "level": "AAA",
      "status": "does-not-support",
      "notes": "TBD V1",
      "evidence": [],
      "commit": "0000000"
    },
    {
      "id": "2.4.13",
      "name": "Focus Appearance",
      "level": "AAA",
      "status": "does-not-support",
      "notes": "TBD V1",
      "evidence": [],
      "commit": "0000000"
    },
    {
      "id": "2.5.5",
      "name": "Target Size (Enhanced)",
      "level": "AAA",
      "status": "does-not-support",
      "notes": "TBD V1",
      "evidence": [],
      "commit": "0000000"
    },
    {
      "id": "2.5.6",
      "name": "Concurrent Input Mechanisms",
      "level": "AAA",
      "status": "does-not-support",
      "notes": "TBD V1",
      "evidence": [],
      "commit": "0000000"
    },
    {
      "id": "3.1.3",
      "name": "Unusual Words",
      "level": "AAA",
      "status": "not-applicable",
      "exception": "content-type",
      "notes": "Falsafa publishes primary-source philosophy across six languages. The corpus is built on technical and unusual vocabulary; identifying every term is contrary to the project's editorial purpose. Partial mitigation planned in V2 via glossary popovers (read_wiki).",
      "evidence": [],
      "commit": "0000000"
    },
    {
      "id": "3.1.4",
      "name": "Abbreviations",
      "level": "AAA",
      "status": "does-not-support",
      "notes": "TBD V1",
      "evidence": [],
      "commit": "0000000"
    },
    {
      "id": "3.1.5",
      "name": "Reading Level",
      "level": "AAA",
      "status": "not-applicable",
      "exception": "content-type",
      "notes": "Falsafa publishes graduate-level primary-source philosophy across six languages. Lowering reading level would require rewriting the corpus and is contrary to the project's editorial purpose. Mitigations: chapter summaries via read_wiki MCP tool; cross-tradition links via TF-IDF.",
      "evidence": [],
      "commit": "0000000"
    },
    {
      "id": "3.1.6",
      "name": "Pronunciation",
      "level": "AAA",
      "status": "not-applicable",
      "exception": "content-type",
      "notes": "Pronunciation aids for non-English terms across six languages (Urdu, Sanskrit, Old English, French, German, Old Javanese) would require pronunciation curation per term per language — content work explicitly deferred. IPA inline annotations may land in V2 or V3.",
      "evidence": [],
      "commit": "0000000"
    },
    {
      "id": "3.2.5",
      "name": "Change on Request",
      "level": "AAA",
      "status": "does-not-support",
      "notes": "TBD V1",
      "evidence": [],
      "commit": "0000000"
    },
    {
      "id": "3.3.5",
      "name": "Help",
      "level": "AAA",
      "status": "does-not-support",
      "notes": "TBD V1",
      "evidence": [],
      "commit": "0000000"
    },
    {
      "id": "3.3.6",
      "name": "Error Prevention (All)",
      "level": "AAA",
      "status": "does-not-support",
      "notes": "TBD V1",
      "evidence": [],
      "commit": "0000000"
    },
    {
      "id": "3.3.9",
      "name": "Accessible Authentication (Enhanced)",
      "level": "AAA",
      "status": "not-applicable",
      "exception": "no-authentication",
      "notes": "No authentication.",
      "evidence": [],
      "commit": "0000000"
    }
  ],
  "section_508": [
    {
      "id": "302.1",
      "name": "Without Vision",
      "status": "does-not-support",
      "notes": "TBD V1 — proved by VoiceOver + NVDA audio recordings",
      "evidence": []
    },
    {
      "id": "302.2",
      "name": "With Limited Vision",
      "status": "does-not-support",
      "notes": "TBD V1",
      "evidence": []
    },
    {
      "id": "302.3",
      "name": "Without Perception of Color",
      "status": "does-not-support",
      "notes": "TBD V1",
      "evidence": []
    },
    {
      "id": "302.4",
      "name": "Without Hearing",
      "status": "supports",
      "notes": "No audio content is published. Site is fully usable without hearing.",
      "evidence": []
    },
    {
      "id": "302.5",
      "name": "With Limited Hearing",
      "status": "supports",
      "notes": "No audio content is published.",
      "evidence": []
    },
    {
      "id": "302.6",
      "name": "Without Speech",
      "status": "supports",
      "notes": "No speech-input or speech-output requirements.",
      "evidence": []
    },
    {
      "id": "302.7",
      "name": "With Limited Manipulation",
      "status": "does-not-support",
      "notes": "TBD V1 — proved by keyboard-only Playwright journeys",
      "evidence": []
    },
    {
      "id": "302.8",
      "name": "With Limited Reach and Strength",
      "status": "does-not-support",
      "notes": "TBD V1",
      "evidence": []
    },
    {
      "id": "302.9",
      "name": "With Limited Language, Cognitive, and Learning Abilities",
      "status": "partial",
      "notes": "Falsafa publishes graduate-level primary-source philosophy. Reading level is content-type-fixed (WCAG 3.1.5 exception). Mitigations include chapter summaries via the read_wiki MCP tool.",
      "evidence": []
    }
  ],
  "en_301_549": [
    {
      "clause": "5.2",
      "name": "Activation of accessibility features",
      "status": "supports",
      "notes": "System preferences (prefers-color-scheme, prefers-contrast, prefers-reduced-motion, forced-colors) are honored without UI interaction. Disabled users get a correctly-themed first load.\n",
      "evidence": [
        {
          "kind": "source",
          "path": "apps/site/src/styles/tokens.css",
          "anchor": "prefers-color-scheme"
        },
        {
          "kind": "source",
          "path": "apps/site/src/styles/tokens.css",
          "anchor": "prefers-contrast"
        },
        {
          "kind": "source",
          "path": "apps/site/src/styles/tokens.css",
          "anchor": "forced-colors"
        },
        {
          "kind": "artifact",
          "path": "docs/accessibility/test-runs/theme-prefs/latest/transcript-synthetic.md"
        }
      ]
    },
    {
      "clause": "5.3",
      "name": "Biometrics",
      "status": "not-applicable",
      "notes": "No biometric authentication. Site has no authentication of any kind.",
      "evidence": []
    },
    {
      "clause": "5.4",
      "name": "Preservation of accessibility information during conversion",
      "status": "not-applicable",
      "notes": "Site does not perform document-to-document conversion.",
      "evidence": []
    },
    {
      "clause": "9",
      "name": "Web (refers to WCAG 2.1)",
      "status": "does-not-support",
      "notes": "TBD V1 — superset claim via WCAG 2.2 AA",
      "evidence": []
    },
    {
      "clause": "11",
      "name": "Software (non-web)",
      "status": "not-applicable",
      "notes": "Falsafa is a web product. The MCP package is covered separately if/when its UI grows.",
      "evidence": []
    },
    {
      "clause": "12.1",
      "name": "Product documentation",
      "status": "does-not-support",
      "notes": "TBD V1 — README + /accessibility page satisfy this",
      "evidence": []
    },
    {
      "clause": "12.2",
      "name": "Support services",
      "status": "supports",
      "notes": "Accessibility issues may be reported via mailto:accessibility@thothica.com or GitHub issue.",
      "evidence": []
    }
  ]
} as ConformanceDoc;
