import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { parseConformanceDoc } from "../parse.js";
import type { ConformanceDoc } from "../types.js";

export function renderMatrixModule(doc: ConformanceDoc): string {
  const json = JSON.stringify(doc, null, 2);
  return `// AUTO-GENERATED by apps/a11y-tools/src/generate/matrix.ts.
// Do not edit by hand. Run: bun a11y:generate matrix.
// Source: docs/accessibility/conformance.yaml

export interface ConformanceCriterion {
  id: string;
  name: string;
  level: "A" | "AA" | "AAA";
  status: "supports" | "partial" | "not-applicable" | "does-not-support";
  exception?: string;
  notes: string;
  evidence: Array<{ kind: "source" | "test" | "artifact"; path: string; lines?: string; anchor?: string }>;
  commit: string;
}

export interface Section508Entry {
  id: string;
  name: string;
  status: ConformanceCriterion["status"];
  notes?: string;
  evidence: ConformanceCriterion["evidence"];
}

export interface EN301549Entry {
  clause: string;
  name: string;
  status: ConformanceCriterion["status"];
  notes?: string;
  evidence: ConformanceCriterion["evidence"];
}

export interface ConformanceDoc {
  meta: {
    standard: string;
    conformance_level: string;
    partial_aaa: boolean;
    last_review: string;
    next_review: string;
    contact: string;
    vpat_version: string;
    jurisdictions: string[];
  };
  criteria: ConformanceCriterion[];
  section_508: Section508Entry[];
  en_301_549: EN301549Entry[];
}

export const CONFORMANCE: ConformanceDoc = ${json} as ConformanceDoc;
`;
}

export async function generate(): Promise<void> {
  const root = process.cwd();
  const doc = await parseConformanceDoc(resolve(root, "docs/accessibility/conformance.yaml"));
  const ts = renderMatrixModule(doc);
  const outPath = resolve(root, "apps/site/src/lib/conformance.generated.ts");
  mkdirSync(dirname(outPath), { recursive: true });
  writeFileSync(outPath, ts);
  console.log(`Generated ${outPath}`);
}
